# git-cliff configuration
# see: https://git-cliff.org/docs/configuration

[git]
commit_parsers = [
    # Exclude release commits.
    { message = "^ops: ?release", skip = true },

    # Conventional commits.
    { message = "^feat", group = "<!-- 0 -->ğŸš€ Features" },
    { message = "^fix", group = "<!-- 1 -->ğŸ› Fixes" },
    { message = "^ops", group = "<!-- 2 -->ğŸ›¡ï¸ Operations" },
    { message = "^docs", group = "<!-- 3 -->ğŸ“š Documentation" },

    # Catch-all.
    { message = ".*", group = "<!-- 100 -->Other Changes" },
]

[changelog]
header = """
This file contains a chronological list of all major changes made to this crate.\n
"""

body = """
{% if version %}\
    ## [{{ version | split(pat="-") | last | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## Unreleased Changes
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""

footer = """
<!-- auto-generated by git-cliff -->
"""